# -*- coding: utf-8 -*-
"""Motivation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFLsm_mNhyVmrRCf3xCp9cjBgPmd7DRy
"""

import pandas as pd
import random

df = pd.read_json("Quotes\quotes.json")

print(df.head())

df.drop('Popularity', axis=1, inplace=True)
print(df.head())

cat = df['Category'].unique()
print(cat)

# #Depreciated :(
# filtered = pd.DataFrame()
# for item in cat:
#     if(item == 'inspiration'):
#         filtered = pd.concat([df[df['Category']=='inspiration'],filtered])
#     elif(item == 'motivation'):
#         filtered = pd.concat([df[df['Category']=='motivation'],filtered])
#     elif(item == 'positive'):
#         filtered = pd.concat([df[df['Category']=='positive'],filtered])
# print(len(filtered))

filtered = df.loc[df['Category'].isin(['motivation','inspiration','positive'])]
print(len(filtered))

filtered = filtered.loc[filtered.astype(str).drop_duplicates().index]
print(len(filtered))

result= filtered.to_json(r"Quotes\filtered.json")

test = pd.read_json("Quotes\\filtered.json")
count = len(test)
num = random.randint(0,count+1)
print(test.iloc[num]['Quote'])



